- no botão nova transação, permitir inserir todos os parâmetros: data, estabelecimento, categoria, fatura, parcelamento. em valor total e valor por mês, preencher automaticamente o segundo conforme o valor inserido no primeiro e vice-versa
- corrigir sugestão: estabelecimento Nova Primavera geralmente é Mercado/Farmácia.
- as compras que foram estornadas não foram computadas. preciso que elas também entrem como transação pendente, com valor negativo.
- transações da NuBank demoram mais de 24h para entrar no pluggy. algum jeito de contornar e tornar real-time, conforme aparece no aplicativo do banco? eu recebo notificações automaticamente no aplicativo do banco toda vez que alguma compra é aprovada ou estornada.
- bradesco demora mais de 48h. algum jeito de contornar? eu recebo mensagens automáticas em sms toda vez que uma transação é aprovada ou estornada.
- alterei a data de fechamento da fatura do bradesco (29) e ele continuou sem exibir valores a partir dessa data. no card da pendência, a data está correta e a fatura correspondente também, mas não é exibido na fatura do mês.
- o bradesco também lança as compras parceladas como se fossem várias compras a vista em meses diferentes. vamos fazer a mesma coisa que fazemos no pix no crédito? eu edito o primeiro, as parcelas são projetadas nos meses seguintes, e as outras pendências relacionadas são excluídas?
- no card de aprovação, exibir nome do cartão.
- no card de aprovação, exibir todos os dados da transação que possivelmente está duplicado. atualmente só exibe cartão, parcelamento e valor por mês
- alerta de duplicidade: transações em cartões diferentes nunca são duplicidades. 
- na aba Todos, adicionar a coluna Cartão, exibindo a qual cartão a transação se refere.
- adicionar parâmetro "cartão" no card de aprovação
- algumas compras do bradesco estão vindo com
- em compras parceladas, manter a data automaticamente igual ao da transação da parcela 1.
- não incluir o prefixo "Pix no Crédito - " como estabelecimento oficial. é só um metadado detalhando o tipo de gasto, mas o estabelecimento oficialmente é o que está após esse prefixo.
